name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout repository code
      uses: actions/checkout///////2v3
      - run: echo "$(cat hello_world.txt)'
